### ISSUE TITLE
Text doesn't fit on 720px screen

### ISSUE THREAD

**Issue by squilter** [DroidPlanner/3DRServices#40]
Stock samsung S3
![screenshot_2015-02-05-19-37-31](https://cloud.githubusercontent.com/assets/2956460/6072353/d12e11c4-ad6e-11e4-9b24-9ee0b01663e8.png)

**Comment by Thalek** [comment]
I have a similar display on my Galaxy S4.

**Comment by ne0fhyk** [comment]
The text is within a scrollview, so it's setup to be scrollable.

**Comment by Thalek** [comment]
Excellent!

**Comment by squilter** [comment]
It is not scrollable on my device.

**Comment by ne0fhyk** [comment]
Fixed by pr #48
