### ISSUE TITLE
Add support for custom camera profiles

### ISSUE THREAD

**Issue by ne0fhyk** [DroidPlanner/3DRServices#61]
See https://github.com/DroidPlanner/droidplanner/issues/1398

**Comment by ne0fhyk** [comment]
@wolkstein PR #63 (version 1.2.9) is adding for custom camera profiles loading.

Similar to DP2, the custom camera profiles should be placed in the `/sdcard/3DRServices/CameraInfo/` directory.

After placing the files, restart `3DR Services` (force stop) to have it pick up the newly added camera profiles.

Version 1.2.9 will be shortly available in the beta channel for testing.

**Comment by wolkstein** [comment]
great and thx a lot :).
