### ISSUE TITLE
Raw Mavlink message cannot be sent

### ISSUE THREAD

**Issue by alextel69** [DroidPlanner/3DRServices#65]
I tried sending raw Mavlink message via Drone.sendMavlinkMessage(). Copter doesn't react. Tried ARM and RC_OVERRIDE messages
Reason: 
sendMavlinkMessage() under the hood sets sysId and compId, but target_system and target_component are left blank
Quickfix: set target_system = 1 of your Mavlink message

**Comment by ne0fhyk** [comment]
Fixed by PR #69
